runtime: go115
main: ./cmd/api-service
service: api
handlers:
  - url: /.*
    script: auto
    secure: always
    redirect_http_response_code: 301
vpc_access_connector:
  #update project name for manual deploy (addressed in CI)
  name: projects/solar-fuze-307109/locations/europe-west2/connectors/private-vpc-connector
env_variables:
  #Env variables for connection strings are updated by CI
  CORS_ALLOWED_ORIGINS: "http://localhost:8080,http://localhost:4000,http://localhost:3000"
  GRAPHQL_PLAYGROUND: "true"
  DATABASE_URL: postgresql://user:password@localhost:5432/ams?sslmode=disable
  ELASTICSEARCH_URL: http://localhost:9200
