on:
  push:
    branches:
      - master
      - develop
    tags:
      - v*
  pull_request:
    branches:
      - master
      - develop

jobs:
  build:
    name: 'build'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
      - name: 'Echo test'
        run: |
          echo "Run tests"
      - name: blah
        uses: chrisdickinson/setup-yq@latest
        run: |
        yq --help
        yq e '.vpc_access_connector.name' app.yaml
