on:
  push:
    branches:
      - '*'
defaults:
  run:
    working-directory: /

jobs:
  build:
    name: 'build'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
      - name: 'Echo test'
        run: |
          echo "Run tests"
      - name: install snap
        run: |
          sudo snap install yq
          yq e '.vpc_access_connector.name' app.yaml
      
      - name: yq
        uses: mikefarah/yq@v4.6.1
        with:
          cmd: |
            yq e '.vpc_access_connector.name' app.yaml







#      - name: blah
#        uses: chrisdickinson/setup-yq@latest
#      - name: blah2
#        run: |
#          yq --help
#          yq e '.vpc_access_connector.name' app.yaml
